/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package icmf;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author deepak
 */
public class Customer_Details extends javax.swing.JPanel {

    /**
     * Creates new form Customer_Details
     */
    public Customer_Details() {
        initComponents();
        c=jTextField1.getBackground();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(104, 121, 249));
        setMaximumSize(new java.awt.Dimension(590, 513));
        setMinimumSize(new java.awt.Dimension(590, 513));

        jLabel2.setText("Name :");

        jLabel3.setText("Age :");

        jLabel4.setText("Sex :");

        jLabel5.setText("Mobile Number :");

        jLabel6.setText("Email Address :");

        jLabel7.setText("Address :");

        jTextField1.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if ((0>1) ||
                    (0>1) ||
                    (0>1) ||
                    (jTextField1.getText().length() >=40)) {
                    getToolkit().beep();
                    e.consume();
                }
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female", "Others" }));

        jTextField2.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!((c >= '0') && (c <= '9') ||
                    (c == KeyEvent.VK_BACK_SPACE) ||
                    (c == KeyEvent.VK_DELETE)) ||
                (jTextField2.getText().length() >=10)) {
                getToolkit().beep();
                e.consume();
            }

        }
    });

    jTextArea1.setColumns(20);
    jTextArea1.setRows(5);
    jScrollPane1.setViewportView(jTextArea1);
    jTextArea1.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e) {
            char c = e.getKeyChar();
            if ((0>1) ||
                (0>1) ||
                (0>1) ||
                (jTextArea1.getText().length() >=100)) {
                getToolkit().beep();
                e.consume();
            }
        }
    });

    jSpinner1.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel2)
                .addComponent(jLabel3)
                .addComponent(jLabel4)
                .addComponent(jLabel5)
                .addComponent(jLabel6)
                .addComponent(jLabel7))
            .addGap(68, 68, 68)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                    .addComponent(jTextField3))
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(75, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel6)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(53, Short.MAX_VALUE))
    );

    jLabel1.setFont(new Font("Arial",Font.BOLD,15));
    jLabel1.setText("Customer Details");

    jButton1.setText("Cancel");
    jButton1.setPreferredSize(new java.awt.Dimension(70, 30));
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });

    jButton2.setText("Next");
    jButton2.setPreferredSize(new java.awt.Dimension(70, 30));
    jButton2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(225, 225, 225)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(196, 196, 196)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(42, 42, 42)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(9, 9, 9)
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(28, 28, 28)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(29, Short.MAX_VALUE))
    );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       
        if(!check())
            return;
        
        
        
        
        customer.name=(String)jTextField1.getText();
        customer.Email_Address=(String)jTextField3.getText();
        customer.Address=(String)jTextArea1.getText();
        customer.Mobile_No=(String)jTextField2.getText();
        customer.Age=(int)jSpinner1.getValue();
        customer.Sex=(String)jComboBox2.getSelectedItem();
        jTextField1.setText("");
        jTextField3.setText("");
        jTextField2.setText("");
        jTextArea1.setText("");
        jSpinner1.setValue(0);
        jComboBox2.setSelectedItem("Male");
        /*
                Setting up the customer requirement based on the present system 
                configuratiion
        */
        
        icmf.System s = null ;
        try {
                    FileInputStream fi = new FileInputStream(new File("System_Info_File.dat"));
                    ObjectInputStream oi = new ObjectInputStream(fi);

                    s=(icmf.System) oi.readObject();
                    oi.close();
                    fi.close();

                } catch (FileNotFoundException e) {
                    java.lang.System.out.println("File not found");
                }catch (IOException e) {
                    java.lang.System.out.println("Error initializing stream");
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Main_Panel.class.getName()).log(Level.SEVERE, null, ex);
                }
        
        int y=customer_Requirements1.jComboBox1.getItemCount();
        for(int i=1;i<y;i++){
            customer_Requirements1.jComboBox1.removeItemAt(1);
        }
        if(s.no_Browsing!=0){
            customer_Requirements1.jComboBox1.addItem("Browsing System");
        }
        if(s.no_acaedmic!=0){
            customer_Requirements1.jComboBox1.addItem("Academics System");
        }
        if(s.no_gaming!=0){
            customer_Requirements1.jComboBox1.addItem("Gaming System");
        }
        y=customer_Requirements1.jComboBox3.getItemCount();
        for(int i=1;i<y;i++){
            customer_Requirements1.jComboBox3.removeItemAt(1);
        }
        if(s.no_color_printer!=0){
            customer_Requirements1.jComboBox3.addItem("Color Print");
        }
        if(s.no_plain_printer!=0){
            customer_Requirements1.jComboBox3.addItem("Plain Print");
        }
        y=customer_Requirements1.jComboBox4.getItemCount();
        for(int i=1;i<y;i++){
            customer_Requirements1.jComboBox4.removeItemAt(1);
        }
        if(s.no_black_xerox!=0){
            customer_Requirements1.jComboBox4.addItem("Black-White");
        }
        if(s.no_color_xerox!=0){
            customer_Requirements1.jComboBox4.addItem("Color");
        }
        
        
        
        CardLayout cardLayout = (CardLayout) jButton2.getParent().getParent().getLayout();
        cardLayout.show(jButton2.getParent().getParent(), "card4");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField3.setText("");
        jTextField2.setText("");
        jTextArea1.setText("");
        jSpinner1.setValue(0);
        jComboBox2.setSelectedItem("Male");
        jTextField1.setBackground(c);
        jTextField2.setBackground(c);
        jTextField3.setBackground(c);
        jTextArea1.setBackground(c);
        CardLayout cardLayout = (CardLayout) jButton2.getParent().getParent().getLayout();
        cardLayout.show(jButton2.getParent().getParent(), "card2");
    }//GEN-LAST:event_jButton1ActionPerformed
    
    //Custom Coded Functions
    
    public void initialize_parameters(icmf.Customer customer,icmf.Customer_Requirements customer_Requirements1){
        
        this.customer=customer;
        this.customer_Requirements1=customer_Requirements1;
    }
    
    public boolean isValidEmailAddress(String email) {
           String ePattern = "^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\])|(([a-zA-Z\\-0-9]+\\.)+[a-zA-Z]{2,}))$";
           java.util.regex.Pattern p = java.util.regex.Pattern.compile(ePattern);
           java.util.regex.Matcher m = p.matcher(email);
           return m.matches();
    }
    
   
    private boolean check(){
        int flag=1;
        if(jTextField1.getText().equals("")){
            flag=0;
            //jTextField1.setBackground(Color.RED);
            //JOptionPane.showMessageDialog(null, "Please Fill The Name Field ","Error", JOptionPane.INFORMATION_MESSAGE);
        }
        
        if(jTextField2.getText().length()!=10){
            flag=0;
            //jTextField2.setBackground(Color.RED);
            //JOptionPane.showMessageDialog(null, "Please enter correct number ","Error", JOptionPane.INFORMATION_MESSAGE);
        }
        
        if(jTextArea1.getText().equals("")){
            flag=0;
            //jTextArea1.setBackground(Color.RED);
            //JOptionPane.showMessageDialog(null, "Please Fill The Address Field ","Error", JOptionPane.INFORMATION_MESSAGE);
        }
        
        if(!isValidEmailAddress(jTextField3.getText())){
            flag=0;
            //jTextField3.setBackground(Color.RED);
            //JOptionPane.showMessageDialog(null, "Please Enter valid Email Address ","Error", JOptionPane.INFORMATION_MESSAGE);
        }
        
        
        if(flag==0){
            JOptionPane.showMessageDialog(null, "Please check if  all the fields are filled and you have entered  valid Email Address and Mobile number  !!!!","Error", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        return true;
    }
    //End of Custom Coded Functions

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

    // Variables declaration - Custom Code
    private icmf.Customer customer;
    public icmf.Customer_Requirements customer_Requirements1;
    Color c;
    // End of variables declaration 
}
